//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHocSinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int ID { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> ClassLevel { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<int> MaxTotal { get; set; }
    }
}
