//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHocSinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CUSId { get; set; }
        public string CUSKey { get; set; }
        public string CusName { get; set; }
        public Nullable<int> mobileno { get; set; }
        public string Gender { get; set; }
    }
}
