//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHocSinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public int ID { get; set; }
        public string StudentID { get; set; }
        public string SubjectID { get; set; }
        public Nullable<int> Semester { get; set; }
        public Nullable<double> Test15Minutes { get; set; }
        public Nullable<double> Test45Minutes { get; set; }
        public Nullable<double> TestSemester { get; set; }
        public Nullable<double> Average { get; set; }
        public Nullable<int> Flag { get; set; }
        public string StudenJoinID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ClassID { get; set; }
    }
}
