//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHocSinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public int ID { get; set; }
        public string SubjectID { get; set; }
        public string SubjectName { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Level1 { get; set; }
        public Nullable<int> Level2 { get; set; }
        public Nullable<int> Level3 { get; set; }
        public Nullable<int> Period { get; set; }
    }
}
