//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHocSinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string FullName { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public Nullable<int> Role { get; set; }
        public string address { get; set; }
        public string phonenumber { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<int> gender { get; set; }
    }
}
